### ISSUE TITLE
Will only start in the gameboy color version, but I want to use OG gameboy palettes.

### ISSUE THREAD

**Issue by brabtete** [bardeci/dot-matrix-simulator#1]
I've recently downloaded the LSDJ demo rom and I opened it and it automatically went to the gbc version instead. It was a .gb file so I hoped it'd open to that so I could use some good looking palettes with it, because I'm just that picky and the gbc colors are bad looking to me. Anyways, is there any way I could stop it from opening as a gbc game and instead play it as an og gb game? Thanks in advance.

**Comment by hi-ban** [comment]
I'm working in a solution which will allow you to select to run in DMG or GBC mode when a ROM supports both systems (which is the case of LSDJ).
Greetings!

**Comment by bardeci** [comment]
Solved in https://github.com/bardeci/dot-matrix-simulator/releases/tag/20200115
