### ISSUE TITLE
Adding option for fast-forward to toggle, as well as add turbo buttons

### ISSUE THREAD

**Issue by Toblerone1** [bardeci/dot-matrix-simulator#11]
It would be really nice, especially for pokemon, to be able to make the fast forward button be a toggle instead of having to hold the L button down as long as I want to fast forward. As well that an option to make X and Y turbo A and B instead of just another A and B, or the same for the other button layout, it would be very convenient. Really enjoying the improvements the emulator has over the stock one and hope to see it improve more, thanks

**Comment by bardeci** [comment]
Unfortunately, it looks like i'd have to rewrite quite a lot of the fast forward code to make it work in both hold and toggle modes. I will look more deeply into it, but dont put your hopes on it being done, or at least on being done fast.
As for the turbo buttons, i did want to have them, but it's more of the same. See https://github.com/bardeci/gambatte-dms/issues/9

Sorry.

**Comment by Toblerone1** [comment]
Ouch, oh well thanks

**Comment by bardeci** [comment]
Fast forward toggle is now available as an option: https://github.com/bardeci/gambatte-dms/releases/latest

As for the turbo buttons, i have been trying different things with no success. I'll keep investigating.

**Comment by ElSombrero** [comment]
Hey @bardeci I know that you have looked into auto fire more than once, but as someone with a physical disability it would be a huge boon
Is the challenge given the current architecture of gambatte? Cheers!
