### ISSUE TITLE
Game Boy Advance

### ISSUE THREAD

**Issue by tylibra2** [bardeci/dot-matrix-simulator#13]
Add Game Boy Advance to gambatte-dms!

**Comment by bardeci** [comment]
Gambatte is a GB/GBC emulator. If you want to play GBA, you should use either ReGBA or GPSP

**Comment by tylibra2** [comment]
They said that you would put support for GBA in gambatte-dms on Reddit.

**Comment by bardeci** [comment]
Gambatte is a GB/GBC emulator. It does not emulate GBA, SNES or other consoles.

**Comment by tylibra2** [comment]
SA_FL
While there is only one CFW and it works well there are a few things that you should do. The first is to grab fceux_improved_v2 and replace the existing fceux emulator with it (I suggest renaming the original fceux to fceux.orig). The second is to get the latest versions of Gambatte and snes9x and install them. Also be sure to put snesadvance.dat in the .snes9x4d-ng folder. Also note that Gambatte is probably going to get the ability to simulate a GBA soon (for GB/GBC games that detect GBA hardware and unlock bonuses, NOT actually running GBA games). I saw it on a Reddit post

**Comment by bardeci** [comment]
In some GB emulators, it's possible to unlock some features from some GBC games (actually like only 3 or 4 games from the whole catalog) which are only present when you play those GBC games using a GBA.
I'm looking into adding that ability to Gambatte, but that has nothing to do with emulating GBA or playing GBA games.

**Comment by SteveCraft27** [comment]
On SGB Enhanced: Unlocks Battle Mode From Bomberman GB (USA) / Bomber Man GB 2 (Japan)
