### ISSUE TITLE
Button layout for LSDJ

### ISSUE THREAD

**Issue by Skycstls** [bardeci/dot-matrix-simulator#14]
So, a few users are trying to use LSDJ to make music using the rg350, so far the emulator works nice, ive been using the original DMG and it sound emulation is really nice, but we have problems with how the key layout is arranged, we use combinations of SELECT+DIRECTION and SELECT+A/ SELECT+B/ SELECT+A+B for moving between screens and copying, pasting and cutting, the alternative version in the menu helps with the navigation but lacks for the combinations for copying, cutting and pasting.
It would be awesome some menu for custon edit the button layout, ive never seen that in a GB emulator for the RG350, or at least another alternative version to have select+start linked to the triggers so we can have the right and left thumb free for those commands.
Thanks for this awesome emulator!

**Comment by bardeci** [comment]
You can use the "Alternate 2" button layout, in which Y/X function as select/start. This extra layout was added as a request from another LSDJ user. See https://github.com/bardeci/gambatte-dms/issues/5

**Comment by jroo** [comment]
The select and start mapping to Y/X is amazing, thank you! Unfortunately, Alternate 2 seems to have A and B flipped on the RG350M with A on the right and B on the left.

**Comment by bardeci** [comment]
A is always on the right and B on the left. It's the normal layout from the original consoles.

**Comment by bardeci** [comment]
oh wait, you meant it's opposite as normal, so A is on left and B is on right. Yeah, you're right. I'll fix that in the next release.

**Comment by jroo** [comment]
Yes, sorry. Thanks!

**Comment by bardeci** [comment]
Solved in new release https://github.com/bardeci/gambatte-dms/releases/latest

**Comment by jroo** [comment]
It's perfect, thank you.
