### ISSUE TITLE
DMG games in GBC

### ISSUE THREAD

**Issue by Ninoh-FOX** [bardeci/dot-matrix-simulator#17]
Would it be possible to add an option to put GB games in GBC mode through the bios as in the retroarch emulator?

**Comment by bardeci** [comment]
Puedes usar castellano si quieres. ¿Puedes explicarte mejor? ¿A qué te refieres exactamente com "modo GBC"?

**Comment by Ninoh-FOX** [comment]
Menos mal, veras, en el core de este emulador en Retroarch tiene tres opciones en el tema de las bios.

El normal arranca con el boot de la consola, GB como GB y GBC como GBC, como el tuyo. Luego tiene opciones de gbc o sgb. Bueno, pues en RA tu puedes puedes elegir que los juegos de GB arranquen con el boot de GBC, en este modo, te permite elegir las doce paletas que la GBC ofrece a los juegos de GB pulsado el dpad mas A o B durante el boot de arranque..

Es eso a lo que me refiero entonces, si se podria añadir una opcion en el apartado de la configuracion de bios donde te permita arrancar los juegos de GB como si fuera una consola GBC. Eso seria genial.

**Comment by bardeci** [comment]
Cuando implementé el soporte para BIOS, esto se podía hacer. Pero lo tuve que anular porque daba problemas con los savestates.
Por ejemplo, si arrancabas un juego en modo GBC y activabas una paleta de la BIOS en el arranque, cualquier savestate que guardaras solo funcionaba correctamente si, al cargarlo de nuevo, estabas en modo GBC y con la misma paleta activada. Si tenías cualquier otra paleta activa, o ninguna, o no estabas en modo GBC, el juego aparecía corrupto al cargar el savestate (en la pantalla solo se veía "basura").
Por ese motivo tuve que anular la función. Si la hubiera dejado activa, muchos usuarios hubieran tenido problemas.
En cualquier caso, puedes conseguir el mismo resultado usando paletas externas y configurando los juegos por separado para que cada uno use la paleta que quieras.

**Comment by Ninoh-FOX** [comment]
Oh, vaya, tiene sentido, no he probado si esto se los save state afecta del mismo modo a la version de RA. Visto, pues cierro el hilo, a ver si en un futuro.

He comprobado los save/load state en RA cargando diferentes paletas, y no hay fallos, simplemente te carga la paleta que estaba activa en el momento del save, por si te interesa mirarlo.
