### ISSUE TITLE
GBC games with GB support have not GBC color palettes

### ISSUE THREAD

**Issue by feurigel** [bardeci/dot-matrix-simulator#18]
When I run a GBC game with GB support (eg. Wario Land 2) it only uses a monochrome screen and does not use a GBC color palette. Used filetype is "gbc".

OhBoy works correctly and uses gbc colors.
I think that Gambatte SDL with Rumble support (available on MiyooCFW 1.3.3) uses sgb colors.

Tested with: Release 20210116
On: Pocket Go v1 with MiyooCFW 1.3.3

OhBoy:
![wario-land-2-ohboy](https://user-images.githubusercontent.com/25955045/111083372-91ac7680-850d-11eb-8bed-3e361d3b29a8.png)

Gambatte-DMS:
![wario-land-2-gambatte](https://user-images.githubusercontent.com/25955045/111083382-9a04b180-850d-11eb-8d81-cb89edc707d4.png)

Gambatte-SDL:
![wario-land-2-gambatte-sdl](https://user-images.githubusercontent.com/25955045/111083390-a1c45600-850d-11eb-8aa0-cd5f437b87a6.png)

**Comment by bardeci** [comment]
- Go to Menu > Settings > System, and select "Priority GBC".
- Save the settings.
- Restart the emulator.

The Priority option lets you choose the preferred system (GB or GBC) to use in those rare cases when a ROM supports both GB and GBC modes.

**Comment by feurigel** [comment]
Ah, thanks. This works!
I tried already the Priority GBC option and restart the game in the emulator.
But I don't tried to save this option and restart the emulator, haha... 😃

**Comment by bardeci** [comment]
Cool! I guess the issue is solved then ;-)
