### ISSUE TITLE
How to install for bitboy/playgo?

### ISSUE THREAD

**Issue by adi170-alt** [bardeci/dot-matrix-simulator#19]
The only files in those zip files are:
gambatte-dms and gambatte-dms.png
i need a opk file😫

**Comment by bardeci** [comment]
The bittboy/pocketgo devices have never supported the OPK format. Only the OpenDingux/RetroFW devices support OPKs.

**Comment by adi170-alt** [comment]
Oh, I did not know that, I have a playgo and that is like a cheaper version of the pocketgo2, and it is the same, but it runs on opendinux https://github.com/Ninoh-FOX/POCKETGO2_ROGUE_CFW on this software, I will just use the multi version because that one works, the fabric software that came with my device was also just opendinux

**Comment by bardeci** [comment]
Oh, so you have a PlayGo. For some reason i thought you had a bittboy.
If you have a PlayGo then yes, the multi version is what you need. In fact, the PlayGo is already listed as compatible with the multi version.
