### ISSUE TITLE
D-Pad or Joystick consecutive press doesn't register

### ISSUE THREAD

**Issue by PatriciaRC** [bardeci/dot-matrix-simulator#2]
When pressing a direction on the D-Pad or Joystick and then a consecutive different one without releasing the first, the second press doesn't register.

Tested on the system's test app and other emulators and the same input works.

Example shown in video https://youtu.be/2yheQdWC5pc

**Comment by bardeci** [comment]
That's how the GB Tetris game works, so only Nintendo can fix it. You can try the GB Tetris in any other emulator in PC and the behaviour will be the same. 

If you try the same in any other games like for example Link's Awakening or Gauntlet 2 you will see the emulator inputs work correctly.

**Comment by PatriciaRC** [comment]
I see. Thanks for the explanation. It seems I didn't remember it correctly after so many years.
