### ISSUE TITLE
Gambatte 0.5.1 Update Request: Add Support For SGB Enhanced

### ISSUE THREAD

**Issue by ghost** [bardeci/dot-matrix-simulator#28]
Add Support For SGB Enhanced
Add SGB In Emulated Hardware
Add SGB Borders On/Off
![Screenshot_20220224-214656~2](https://user-images.githubusercontent.com/99989661/156879090-949610b7-3c06-43a8-ba69-9f997a60e296.jpg)
![Screenshot_20220224-214702~2](https://user-images.githubusercontent.com/99989661/156879094-5c901366-f817-4e00-be2f-41e30973c1ce.jpg)
![Screenshot_20220305-111146~2](https://user-images.githubusercontent.com/99989661/156879100-cce9d9ec-1670-48ef-bc1d-556453523724.jpg)

**Comment by hi-ban** [comment]
As much as i'd like to have such feature, that would require adding SNES emulation. So sadly it's not possible.

As for the borders, you can download most of the existing SGB border images from the link below, load them from the emulator menu and save different settings per-game. Alternatively, you can rename the borders with the same name as the ROM you want them to be loaded with, and set the border as "Auto". This way you dont need to save per-game settings for the borders. The manual linked below explains where to store the borders so you can use them in the emulator.

SGB BORDERS: http://www.vgmuseum.com/features/sgb/
MANUAL: https://github.com/bardeci/gambatte-dms/blob/master/dist/manual.txt

**Comment by ghost** [comment]
Do Not Add SGB Borders.
Add Support For SGB Enhanced And Add SGB On Emulated Hardware. Why mGBA, VBA-M, SameBoy Core Has SGB Enhanced Support, SGB On Emulated Hardware.

**Comment by ghost** [comment]
Yes. SGB Enhanced Also Works On GBC Emulators Without SNES Emulation Like SameBoy, VBA-M, mGBA Cores.

**Comment by hi-ban** [comment]
Well, in that case you can use those emulators.

**Comment by ghost** [comment]
Add SGB In Emulated Hardware, Add Support For SGB Enhanced On Gambatte 0.5.1 Update.

**Comment by SopTheSop27** [comment]
It's Coming SGB Enhanced Games On Gambatte 0.5.1 Core Update. And Fix Bug On Bomberman Collection (Japan), Bomberman Selection (Korea), Super Chinese 1.2.3 (Japan)

**Comment by SopTheSop27** [comment]
@bardeci It's Coming SGB Enhanced Games On Gambatte 0.5.1 Core Update. And Fix Bug On Bomberman Collection (Japan), Bomberman Selection (Korea), Super Chinese 1.2.3' (Japan)

**Comment by hi-ban** [comment]
If you can implement it, feel free to add a pull request with working code commits and i will check it out.
