### ISSUE TITLE
Some ideas to improve

### ISSUE THREAD

**Issue by villazeros** [bardeci/dot-matrix-simulator#3]
Hi, I would like to know if it will be possible to add these features:

- Fast forward speed intervals (x2, x3, x4, x6, x8)
- Fast forward toggle option
- Button mapping

Thanks

**Comment by bardeci** [comment]
Fast forward is already working at the max speed these CPUs (jz4760/jz4770) can process. So having different speeds as an option wouldnt really change the speed at which fast forward works in your console.

At some point i tried a build with toggle option, but being it a toggle it can happen that you accidentally press the button and you end up fastforwarding a chunk when you didnt really want to, or just more than you really want. In my tests it was much more precise and intuitive to only fast forward while you are pressing the button.

There is already an option to invert the button mapping layout, so you can select between BAAB and ABBA button layouts.

**Comment by villazeros** [comment]
Thanks for explaining the max speed, but I think for some games it would be useful to speed up the game a bit, not at max speed. I also think it would be useful in some cases having the toggle option.

**Comment by bardeci** [comment]
Since questions have been answered and suggestions have been noted, i will consider this as closed.
Greetings!
