### ISSUE TITLE
SGB Enhanced Support

### ISSUE THREAD

**Issue by ghost** [bardeci/dot-matrix-simulator#30]
Add SGB Enhanced Support And SGB In Emulated Hardware. On SGB Enhanced: It Unlocks Some Features In Some Games: For Example: Bomberman GB (USA)/Bomber Man GB 2 (Japan) On SGB Enhanced Has Battle. On GB Has No Battle

GB:
![Screenshot_20220409-080925~3](https://user-images.githubusercontent.com/103258834/162559384-fabcd8d5-2485-4516-8c7f-67577c1de095.jpg)

SGB (With Battle):
![Screenshot_20220409-081020~3](https://user-images.githubusercontent.com/103258834/162559391-1f1675cf-5ac5-473f-ae90-2eb904a49d31.jpg)

**Comment by bardeci** [comment]
There are currently no plans to add this feature.

**Comment by ghost** [comment]
SGB Enhanced Looks Like:
![Screenshot_20220411-224221~2](https://user-images.githubusercontent.com/103258834/162830561-c26b022f-347b-4199-8f41-db984fa071ae.jpg)
![Screenshot_20220411-224432~2](https://user-images.githubusercontent.com/103258834/162830577-3d90cef4-a779-4c77-bd24-65ca74c2d7f5.jpg)
![Screenshot_20220411-224240~2](https://user-images.githubusercontent.com/103258834/162830592-1a7dc1c9-b809-44db-9b15-aa0b53235d0f.jpg)
![Screenshot_20220411-224255~2](https://user-images.githubusercontent.com/103258834/162830609-e7d9ccb8-c08e-49ff-8ead-56b2c15ba0b9.jpg)
![Screenshot_20220411-224315~2](https://user-images.githubusercontent.com/103258834/162830634-7a8d1e2e-b1f6-4f94-949a-2fdfb29a5d41.jpg)
![Screenshot_20220411-224332~2](https://user-images.githubusercontent.com/103258834/162830677-b4e17274-1f0c-4505-9898-2d0bd70ad5ce.jpg)
![Screenshot_20220411-224359~2](https://user-images.githubusercontent.com/103258834/162830689-9445c1c6-8a3c-4dab-86f1-34b15cacbf48.jpg)
![Screenshot_20220411-224414~2](https://user-images.githubusercontent.com/103258834/162830699-9815aac0-3a02-4c79-88e0-72e2bc9d56eb.jpg)
![Screenshot_20220411-224456~2](https://user-images.githubusercontent.com/103258834/162830709-def89799-4218-4131-ba7a-0bfc7225f42f.jpg)
![Screenshot_20220411-224511~2](https://user-images.githubusercontent.com/103258834/162830720-33b37acf-cba4-4548-aad7-6e061ad68cc5.jpg)
![Screenshot_20220411-224543~2](https://user-images.githubusercontent.com/103258834/162830731-1f284378-3166-48ff-9120-f61dc4ccdc8b.jpg)
![Screenshot_20220411-224619~2](https://user-images.githubusercontent.com/103258834/162830740-813549b8-b0c9-4dd2-bd4b-6f1d62e3c7f8.jpg)
![Screenshot_20220411-224643~2](https://user-images.githubusercontent.com/103258834/162830758-defe3a16-fe30-4009-8239-f4951d41b4a9.jpg)
![Screenshot_20220411-224651~3](https://user-images.githubusercontent.com/103258834/162830772-f7339594-eddd-48de-877e-02a7422b9f78.jpg)
![Screenshot_20220411-224708~2](https://user-images.githubusercontent.com/103258834/162830784-9b10a1e4-f6c5-411a-9185-81ea70075806.jpg)
![Screenshot_20220411-224733~2](https://user-images.githubusercontent.com/103258834/162830792-3c1da320-b949-4d92-b9fb-81460cff825e.jpg)
![Screenshot_20220411-224742~2](https://user-images.githubusercontent.com/103258834/162830803-373f8c32-5ee2-4e62-b901-911b72bd5ae5.jpg)
![Screenshot_20220411-224744~2](https://user-images.githubusercontent.com/103258834/162830812-8a7cb726-f361-42bd-adf3-da9066cde81c.jpg)
![Screenshot_20220411-224755~2](https://user-images.githubusercontent.com/103258834/162830823-a766209d-965f-40bf-97da-bf6241c1fb45.jpg)
![Screenshot_20220411-224758~2](https://user-images.githubusercontent.com/103258834/162830836-d44028c5-fbe9-4452-9c47-8b9f93ebfbf4.jpg)

SGB Enhanced Feature Will Be In Emulated Hardware: Auto & SGB.

Emulated Hardware:

Auto
GB (Classic Game Boy)
SGB (Super Game Boy Enhanced From SNES)
GBC (Game Boy Color)
GBA (Game Boy Advance Enhanced For Unlocked Some Feature In Some GBC Games)

Super Game Boy Enhanced Can Be Used In Some Game Boy / Color Games.
