### ISSUE TITLE
Do you have plan to add Super Game Boy "emulation" for SGB enhanced GB games

### ISSUE THREAD

**Issue by ghost** [bardeci/dot-matrix-simulator#38]
@bardeci @hi-ban In Options > System > Emulated Hardware

> Auto
> GB
> **SGB**
> **SGB2**
> GBC
> GBA

SGB emulation mode is for **Super Game Boy enhanced Original Game Boy games: SGB Borders, SGB Color Palettes**

SGB Enhanced for example: Kirby's Dream Land 2 (GB) (SGB Enhanced), Mega Man V (GB) (SGB Enhanced), Donkey Kong 94' (GB) (SGB Enhanced), ect...

Game Boy emulation
![Mega Man V (U)  S ! _1659195683405](https://user-images.githubusercontent.com/110131975/181924981-5736e279-a01a-4ba7-b943-3fcf6fc4ff4f.png)

Super Game Boy emulation
![Mega Man V (U)  S ! _1659195723044](https://user-images.githubusercontent.com/110131975/181924982-4eb7ec40-8f93-4c8b-b5c1-62d5498c5c93.png)

Super Game Boy emulation with SGB Borders
![Mega Man V](https://user-images.githubusercontent.com/110131975/181924989-45548c59-2285-4836-a177-5a37a70dcff8.png)

I made a pull request #37

**Comment by bardeci** [comment]
Nope, it's not planned to add that feature, sorry.
