### ISSUE TITLE
Better control remapping

### ISSUE THREAD

**Issue by aphexetwine** [bardeci/dot-matrix-simulator#5]
This is not so much an issue but a much needed feature for LSDJ users.
I have an Anbernic RG350 with very stiff Select and Start buttons. I wish I could assign their functions to the spare X and Y buttons or to the shoulder buttons (I have R2 and L2), or at the very least invert their functions since Select is used more often in LSDJ than Start.
Could we see an implementation of this in the next release of Gambatte?

**Comment by bardeci** [comment]
I dont promise anything, but i will look into it.

**Comment by aphexetwine** [comment]
Thank you. I believe this would fit perfectly within the Controls submenu

**Comment by bardeci** [comment]
Added an extra "Alternate 2" button layout which mirrors Select/Start into X/Y. Available right now in the latest release. I think this solves this issue.

**Comment by bardeci** [comment]
Issue is solved now.
