### ISSUE TITLE
auto fire and cheat code save.

### ISSUE THREAD

**Issue by Cibomatto2002** [bardeci/dot-matrix-simulator#9]
Could we see one day auto fire? and cheat code saving ? :)

anyways keep up the good work on the fine emulator i use it daily. on my pocket go 2

**Comment by bardeci** [comment]
Probably not, for the two of them, sorry.
It would require too much work for the small return. So unfortunately it's not worth it.

**Comment by Cibomatto2002** [comment]
Ok thanks for your time 😊

**Comment by bardeci** [comment]
I have already looked into autofire more than once, but unfortunately it's not a trivial thing to implement it. Sorry.
